"""Public API contracts, options, and compiler facade for BuildCompiler."""

from buildcompiler.errors import (
    BuildCompilerError,
    SynBioHubAuthenticationError,
    SynBioHubConfigurationError,
    SynBioHubError,
    SynBioHubNetworkError,
    SynBioHubResourceError,
    SynBioHubResponseError,
)
from buildcompiler.inventory import index_collections

from .compiler import (
    BuildCompiler,
    assembly_lvl1,
    assembly_lvl2,
    domestication,
    full_build,
    plating,
    transformation,
)
from .options import (
    ApprovalOptions,
    BuildOptions,
    CombinatorialOptions,
    DomesticationOptions,
    ExecutionOptions,
    Lvl2SearchOptions,
    PlanningOptions,
    ProtocolMode,
    ProtocolOptions,
    ReagentOptions,
    ReportingOptions,
    SelectionOptions,
    TransformationOptions,
)
from .serialization import (
    SCHEMA_VERSION,
    SerializationError,
    deserialize_build_plan,
    dumps_json_dto,
    serialize_approval,
    serialize_backbone,
    serialize_build_plan,
    serialize_build_request,
    serialize_build_result,
    serialize_missing_input,
    serialize_plasmid,
    serialize_reagent,
    serialize_report,
    serialize_stage_result,
    serialize_strain,
    serialize_summary,
    serialize_unsupported_planning_record,
    serialize_warning,
    to_json_dto,
)

__all__ = [
    "BuildCompiler",
    "BuildCompilerError",
    "ApprovalOptions",
    "BuildOptions",
    "CombinatorialOptions",
    "DomesticationOptions",
    "ExecutionOptions",
    "Lvl2SearchOptions",
    "PlanningOptions",
    "ProtocolMode",
    "ProtocolOptions",
    "ReagentOptions",
    "ReportingOptions",
    "SelectionOptions",
    "TransformationOptions",
    "SCHEMA_VERSION",
    "SerializationError",
    "SynBioHubAuthenticationError",
    "SynBioHubConfigurationError",
    "SynBioHubError",
    "SynBioHubNetworkError",
    "SynBioHubResourceError",
    "SynBioHubResponseError",
    "assembly_lvl1",
    "assembly_lvl2",
    "domestication",
    "full_build",
    "index_collections",
    "plating",
    "transformation",
    "deserialize_build_plan",
    "dumps_json_dto",
    "serialize_approval",
    "serialize_backbone",
    "serialize_build_plan",
    "serialize_build_request",
    "serialize_build_result",
    "serialize_missing_input",
    "serialize_plasmid",
    "serialize_reagent",
    "serialize_report",
    "serialize_stage_result",
    "serialize_strain",
    "serialize_summary",
    "serialize_unsupported_planning_record",
    "serialize_warning",
    "to_json_dto",
]
